"""create table matakuliah

Revision ID: 2e89608b15a9
Revises: c6d4142d9c74
Create Date: 2025-11-24 02:44:43.382196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e89608b15a9'
down_revision = 'c6d4142d9c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
