"""create table matakuliah

Revision ID: 3d5b179b0730
Revises: 2e89608b15a9
Create Date: 2025-11-24 02:46:33.625570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5b179b0730'
down_revision = '2e89608b15a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
